### PR TITLE
add ephemera+inventory+subinventory from Strukturdatenset

### PR DESCRIPTION
**Pull request by bertsky**
Somehow these were missing.

### CODE REVIEW

**Comment by bertsky** [comment]
Perhaps we should also allow `colour_checker`?

Also, in [DFG-Viewer](https://github.com/slub/slub_digitalcollections/blob/d511e7ebdddba4b9ea344eba5e5b311eb1e41c16/Resources/Private/Language/locallang_kitodo.xlf#L282C1-L287) there seems to be support for an additional `multipart_manuscript` and `manuscript_part` (but not in [kitodo-presentation](https://github.com/kitodo/kitodo-presentation/blob/9113a5e647b9142dde98e09a03a18d53d99bb077/Resources/Private/Data/StructureDefaults.php)...).

Then again, looking from [DDB side](https://wiki.deutsche-digitale-bibliothek.de/pages/viewpage.action?pageId=78512424), we are missing `table_of_contents` (but isn't that just `contents`?), `review` and `part` here. (But I don't understand how that relates to the existing [formal vocabulary](http://ddb.vocnet.org/hierarchietyp)...)

**Comment by bertsky** [comment]
> Also, in [DFG-Viewer](https://github.com/slub/slub_digitalcollections/blob/d511e7ebdddba4b9ea344eba5e5b311eb1e41c16/Resources/Private/Language/locallang_kitodo.xlf#L282C1-L287) there seems to be support for an additional `multipart_manuscript` and `manuscript_part` (but not in [kitodo-presentation](https://github.com/kitodo/kitodo-presentation/blob/9113a5e647b9142dde98e09a03a18d53d99bb077/Resources/Private/Data/StructureDefaults.php)...).

These can be considered solved, see https://github.com/slub/slub_digitalcollections/pull/68

**Comment by tschleier** [comment]
Thanks for the feedback, we're looking into it.

**Comment by tschleier** [comment]
Before closing this...

> we are missing table_of_contents (but isn't that just contents?)

We have adjusted this type in the new version of the Hierarchietypen in METS/MODS (see [METSMODS_DDBHierarchietypen_v1.4.xlsx](https://wiki.deutsche-digitale-bibliothek.de/download/attachments/78512424/METSMODS_DDBHierarchietypen_v1.4.xlsx?version=2&modificationDate=1709214350236&api=v2)). The schematron validation will be updated very soon.

Additionally, we're planning to provide information about the [DDB Hierarchietyp vocabulary](http://ddb.vocnet.org/hierarchietyp) on the DFG-Viewer website.

**Comment by bertsky** [comment]
@tschleier now I'm confused.

Just to be clear: you are certain that DDB's schematron should **not** support
- ephemera, inventory and subinventory (despite its long-standing use in DFG Viewer)
- review and part (despite being part of DDB Hierarchietyp)
?

Moreover, I would like to note that the [Hierarchietyp vocabulary rendering](http://ddb.vocnet.org/hierarchietyp) is missing a display of the formal identifier (e.g. `multivolume_work` instead of just `Multivolume work` and translations).

**Comment by tschleier** [comment]
@bertsky Hope I can clear this up

> Just to be clear: you are certain that DDB's schematron should not support
>
>    ephemera, inventory and subinventory (despite its long-standing use in DFG Viewer)

Yes, we do not currently support these types in the DDB Hierarchietyp vocabulary.

We have only received a low number ephemera so far that we could not include in the DDB. Not because of the structure type itself but because of the way the hierarchy was constructed in `mets:structMap[@TYPE='LOGICAL']`.
We plan to include `ephemera` and `inventory` eventually. If you have a substantial set of records with these please contact us via [email](mailto:bibliothek@deutsche-digitale-bibliothek.de) and we can discuss the details.

>   review and part (despite being part of DDB Hierarchietyp)

I can see why this is confusing - these are special cases. With the latest update, we now have multiple checks for structure types.

We have the "old" `structMapLogical_05`, which validates against the structural data set of the DFG Viewer, which does not contain these two.
In addition we now have the checks `structMapLogical_24-27` which validate against the [Hierarchietypen in DDB-METS/MODS](https://wiki.deutsche-digitale-bibliothek.de/x/KAGuB) (which is based on the DDB Hierarchietyp vocabulary, taking into account the type of document). These support both types where appropriate.

To avoid this confusion we'll add `review` and `part` to `structMapLogical_05` for the next release and adjust the message accordingly. We'll also check if both can be added to the structural data set of the DFG Viewer.

> Moreover, I would like to note that the [Hierarchietyp vocabulary rendering](http://ddb.vocnet.org/hierarchietyp) is missing a display of the formal identifier (e.g. multivolume_work instead of just Multivolume work and translations).

Sorry, I forgot to mention this. The formal identifiers from structural data set of the DFG Viewer the will soon be added as an  alternative label with the comment `METS`.

**Pull request closed without merging**
